#!/usr/bin/env python3
"""Update _data/survey-stats.yml from a Web3Forms CSV export.

How to use:
  1. Log in at https://app.web3forms.com
  2. Open your CallPlan Survey form → Submissions → Export CSV
  3. Save the file (e.g. submissions.csv) in this repo root or anywhere
  4. Run:
       python3 scripts/update_stats.py submissions.csv
  5. Check the updated _data/survey-stats.yml, then:
       git add _data/survey-stats.yml
       git commit -m "Update survey stats"
       git push

Web3Forms exports one row per submission. The "feature" column contains
comma-separated values for checkbox fields, e.g. "android,ai-summary,widgets".
"""
import csv
import sys
import os
from collections import Counter
from datetime import date

# All valid feature keys (must match name="feature" values in the HTML form)
FEATURE_KEYS = [
    'android',
    'apple-watch',
    'widgets',
    'ai-summary',
    'calendar-sync',
    'whatsapp-teams',
    'team-sharing',
    'transcription',
    'crm',
    'ipad',
    'dark-mode',
    'export-pdf',
]

# Labels must match the existing entries in _data/survey-stats.yml
LABELS = {
    'android':        ('Android-Version',               'Android version',              'Versión Android'),
    'apple-watch':    ('Apple Watch App',                'Apple Watch app',              'App para Apple Watch'),
    'widgets':        ('iOS Home Screen Widgets',        'iOS Home Screen Widgets',      'Widgets en pantalla de inicio'),
    'ai-summary':     ('KI-Gesprächszusammenfassung',   'AI call summary',              'Resumen IA de llamadas'),
    'calendar-sync':  ('Google Calendar / Outlook Sync','Google Calendar / Outlook sync','Sincronización Google Calendar / Outlook'),
    'whatsapp-teams': ('WhatsApp / Teams Integration',  'WhatsApp / Teams integration', 'Integración WhatsApp / Teams'),
    'team-sharing':   ('Team-Sharing & Kollaboration',  'Team sharing & collaboration', 'Compartir en equipo y colaboración'),
    'transcription':  ('Offline-Sprachtranskription',   'Offline voice transcription',  'Transcripción de voz sin conexión'),
    'crm':            ('CRM-Integration',               'CRM integration',              'Integración CRM'),
    'ipad':           ('iPad-Version',                  'iPad version',                 'Versión para iPad'),
    'dark-mode':      ('System Dark Mode',              'System dark mode',             'Modo oscuro del sistema'),
    'export-pdf':     ('PDF / CSV Export',              'PDF / CSV export',             'Exportación PDF / CSV'),
}

OUTPUT_PATH = os.path.join(os.path.dirname(__file__), '..', '_data', 'survey-stats.yml')


def parse_csv(path: str) -> tuple[int, Counter]:
    """Return (total_responses, feature_counter)."""
    counts: Counter = Counter()
    total = 0

    with open(path, newline='', encoding='utf-8-sig') as f:
        reader = csv.DictReader(f)

        # Web3Forms column name for a field named "feature" is just "feature".
        # If multiple checkboxes share the same name, Web3Forms joins them with ", ".
        for row in reader:
            total += 1
            raw = row.get('feature', '')
            # split on comma, strip whitespace, ignore empty
            selected = [v.strip() for v in raw.split(',') if v.strip()]
            for feat in selected:
                if feat in FEATURE_KEYS:
                    counts[feat] += 1
                # silently skip unknown values

    return total, counts


def render_yaml(total: int, counts: Counter) -> str:
    today = date.today().strftime('%B %Y')
    lines = [
        f'# Survey statistics – auto-generated by scripts/update_stats.py',
        f'# Source: {total} submissions from Web3Forms  |  Updated: {today}',
        f'# To refresh: export CSV from app.web3forms.com and re-run this script.',
        '',
        f'responses: {total}',
        '',
        'features:',
    ]

    # Sort by count descending so the bars render highest-first
    sorted_keys = sorted(FEATURE_KEYS, key=lambda k: -counts[k])

    for key in sorted_keys:
        pct = round(counts[key] / total * 100) if total > 0 else 0
        de, en, es = LABELS[key]
        lines += [
            f'  - key: {key}',
            f'    label_de: "{de}"',
            f'    label_en: "{en}"',
            f'    label_es: "{es}"',
            f'    pct: {pct}',
            '',
        ]

    return '\n'.join(lines)


def main() -> None:
    if len(sys.argv) != 2:
        print(__doc__)
        sys.exit(1)

    csv_path = sys.argv[1]
    if not os.path.isfile(csv_path):
        print(f'Error: file not found: {csv_path}')
        sys.exit(1)

    total, counts = parse_csv(csv_path)

    if total == 0:
        print('No rows found in CSV. Check that the file is a valid Web3Forms export.')
        sys.exit(1)

    yaml_content = render_yaml(total, counts)

    out = os.path.abspath(OUTPUT_PATH)
    with open(out, 'w', encoding='utf-8') as f:
        f.write(yaml_content)

    print(f'Written: {out}')
    print(f'Total responses: {total}\n')
    print(f'{"Feature":<20}  {"Count":>5}  {"Pct":>4}')
    print('-' * 35)
    for key in sorted(FEATURE_KEYS, key=lambda k: -counts[k]):
        pct = round(counts[key] / total * 100) if total > 0 else 0
        print(f'{key:<20}  {counts[key]:>5}  {pct:>3}%')

    print('\nNext steps:')
    print('  git add _data/survey-stats.yml')
    print('  git commit -m "Update survey stats"')
    print('  git push')


if __name__ == '__main__':
    main()
